In [1]:
import pandas as pd
import numpy as np

from cryptodatapy.extract.datarequest import DataRequest
from cryptodatapy.util.datacatalog import DataCatalog 
from cryptodatapy.extract.getdata import GetData
from cryptodatapy.transform.od import OutlierDetection
from cryptodatapy.transform.impute import Impute
from cryptodatapy.transform.filter import Filter
from cryptodatapy.transform.clean import CleanData, stitch_dataframes
from cryptodatapy.transform.impute import Impute

fatal: bad revision 'HEAD'
Importing plotly failed. Interactive plots will not work.

# Data

In [2]:
dc = DataCatalog()

In [3]:
dc.get_tickers_metadata(cat='eqty').loc[:, 'yahoo_id'].dropna()

ticker
AR_Eqty_Idx            ^MERV
AU_Eqty_Idx            ^AXJO
BE_Eqty_Idx             ^BFX
BR_Eqty_Idx            ^BVSP
CA_Eqty_Idx          ^GSPTSE
CL_Eqty_Idx            ^IPSA
CN_Eqty_Idx        000001.SS
DE_Eqty_Idx           ^GDAXI
EZ_Eqty_Idx        ^STOXX50E
FR_Eqty_Idx            ^FCHI
GB_Eqty_Idx            ^FTSE
HK_Eqty_Idx             ^HIS
ID_Eqty_Idx            ^JKSE
IL_Eqty_Idx        ^TA125.TA
JP_Eqty_Idx            ^N225
MX_Eqty_Idx             ^MXX
MY_Eqty_Idx            ^KLSE
NZ_Eqty_Idx            ^NZ50
RU_Eqty_Idx         IMOEX.ME
SG_Eqty_Idx             ^STI
KR_Eqty_Idx            ^KS11
TW_Eqty_Idx            ^TWII
US_Eqty_Idx            ^GSPC
ZA_Eqty_Idx         ^JN0U.JO
US_Eqty_Vol_Idx         ^VIX
Name: yahoo_id, dtype: object

In [4]:
msci_etf_tickers = dc.get_tickers_metadata(cat='eqty').loc[:, 'tiingo_id'].dropna().values.tolist()

In [5]:
msci_etf_tickers

['SPY',
 'ARGT',
 'UAE',
 'EWA',
 'EWO',
 'EWK',
 'EWZ',
 'EWC',
 'EWL',
 'ECH',
 'MCHI',
 'ICOL',
 'EWG',
 'URTH',
 'EGPT',
 'EEM',
 'EWP',
 'EZU',
 'EWQ',
 'EFNL',
 'EWU',
 'EWH',
 'EIDO',
 'INDA',
 'EIRL',
 'EIS',
 'EWI',
 'EWJ',
 'EWW',
 'EWM',
 'NGE',
 'EWN',
 'ENOR',
 'ENZL',
 'PAK',
 'EPU',
 'EPHE',
 'EPOL',
 'PGAL',
 'QAT',
 'ERUS',
 'KSA',
 'EWS',
 'EWD',
 'EWY',
 'EWT',
 'THD',
 'TUR',
 'EUSA',
 'ACWI',
 'EZA',
 'VXX',
 'IYR',
 'REET']

In [6]:
data_req = DataRequest(source='yahoo', source_tickers=msci_etf_tickers, cat='eqty')

In [7]:
msci_etf_df = GetData(data_req).get_series()

[*********************100%***********************]  54 of 54 completed

In [8]:
msci_etf_df.close.unstack()

ticker,ACWI,ARGT,ECH,EEM,EFNL,EGPT,EIDO,EIRL,EIS,ENOR,...,PAK,PGAL,QAT,REET,SPY,THD,TUR,UAE,URTH,VXX
date,,,,,,,,,,,,,,,,,,,,,
1993-01-29,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1993-02-01,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1993-02-02,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1993-02-03,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1993-02-04,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-16,66.760002,68.5,24.48,94.160004,32.599998,8.06,70.540001,51.580002,26.049999,37.299999,...,63.52,<NA>,58.130001,49.240002,116.610001,18.200001,27.17,26.07,40.66,15.09
2024-09-17,66.43,68.260002,24.15,94.330002,32.549999,8.06,69.709999,51.400002,26.34,37.029999,...,63.220001,<NA>,57.959999,50.299999,116.489998,18.049999,26.969999,25.82,40.439999,15.19
2024-09-18,66.400002,68.769997,24.27,94.199997,32.580002,8.06,69.389999,51.16,26.42,36.990002,...,63.259998,<NA>,57.66,49.880001,116.160004,18.049999,26.889999,25.66,40.900002,15.07
2024-09-19,67.709999,70.150002,24.690001,95.419998,33.09,8.06,71.230003,51.509998,26.74,37.490002,...,63.91,<NA>,58.110001,47.720001,118.230003,18.219999,26.98,25.799999,41.400002,15.41
2024-09-20,68.089996,69.389999,24.549999,94.970001,32.689999,8.06,71.269997,50.66,26.940001,37.040001,...,63.32,<NA>,58.740002,47.43,117.760002,18.15,26.83,25.799999,41.349998,15.4

In [10]:
msci_etf_df.to_parquet('s3://factorlab-data/global_msci_eqty_etf_data_daily.parquet')

In [53]:
msci_etf_df.to_csv('../../../../research_notebooks/msci_etf_df.csv')

In [42]:
eqty_df.to_csv('../../../../research_notebooks/eqty_df.csv')

In [18]:
vix_df = GetData(data_req).get_series()

[*********************100%***********************]  1 of 1 completed

In [26]:
vix_df = vix_df.unstack().close.rename(columns={'^VIX': 'US_Eqty_Vol_Idx'}).stack().to_frame('close')

In [27]:
wld_eqty_df = pd.read_parquet('s3://factorlab-data/global_eqty_data_daily.parquet')

In [31]:
eqty_df = pd.concat([wld_eqty_df, vix_df]).sort_index()

In [40]:
eqty_df.to_csv('../../../../research_notebooks/eqty_df.csv')

In [ ]:
clean = CleanData(fx_df1)

In [ ]:
clean.filter_outliers(od_method='mad', thresh_val=10)

In [ ]:
clean.repair_outliers(imp_method='fcst')

In [ ]:
clean.df.unstack().close.plot(subplots=True, figsize=(15,100))